### ISSUE TITLE
excessive-platform-types.groovy execution fails in Groovy Console

### ISSUE THREAD

**Issue by praveshgupta1993** [sap-commerce-tools/sanecleanup#2]
I am running Hybris v1811
I included sanecleanup extension and as per guided, I ran excessive-platform-types.groovy prior to running system update for hook execution for resources import.
The groovy did not ran successfully and following stacktrace was shown:

`Script execution has failed [reason: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'de.hybris.platform.servicelayer.search.impl.DefaultFlexibleSearchService$$EnhancerBySpringCGLIB$$32fc0d45@252d3db9' with class 'de.hybris.platform.servicelayer.search.impl.DefaultFlexibleSearchService$$EnhancerBySpringCGLIB$$32fc0d45' to class 'groovy.lang.Reference']
`

The other mentioned groovy check-audit.groovy ran successfully.

**Comment by praveshgupta1993** [comment]
The issue is somewhere in below part:
![image](https://user-images.githubusercontent.com/3839056/136468510-c93ea4de-3fb2-4790-99fd-3fc86a12569d.png)

**Comment by praveshgupta1993** [comment]
Fix was to remove 

def @Field 

from field names.

**Comment by mpern** [comment]
Thank you for reporting!
I will add a comment to the script.

FYI, 1811 is [EOL](https://help.sap.com/viewer/dc198ac31ba24dce96149c8480be955f/2105/en-US/1c6c687ad0ed4964bb43d409818d23a2.html)

**Comment by mpern** [comment]
closed - stale
1811 is not maintained anymore
