### ISSUE TITLE
sanecleanup-items.xml is not a valid XML document

### ISSUE THREAD

**Issue by azindal** [sap-commerce-tools/sanecleanup#4]
Getting below error with latest code i.e. 3.4.0 version. Version 3.3.0 was working fine.
Invalid content was found starting with element 'include'. One of '{key}' is expected.
We are using commerce cloud 2005.

Logs:
[schemavalidate] hybris/bin/custom/sanecleanup/resources/sanecleanup-items.xml:11:46: cvc-complex-type.2.4.a: Invalid content was found starting with element 'include'. One of '{key}' is expected.
[schemavalidate] hybris/bin/custom/sanecleanup/resources/sanecleanup-items.xml:23:46: cvc-complex-type.2.4.a: Invalid content was found starting with element 'include'. One of '{key}' is expected.
[schemavalidate] hybris/bin/custom/sanecleanup/resources/sanecleanup-items.xml:35:46: cvc-complex-type.2.4.a: Invalid content was found starting with element 'include'. One of '{key}' is expected.
[schemavalidate] hybris/bin/custom/sanecleanup/resources/sanecleanup-items.xml:45:46: cvc-complex-type.2.4.a: Invalid content was found starting with element 'include'. One of '{key}' is expected.
[schemavalidate] hybris/bin/custom/sanecleanup/resources/sanecleanup-items.xml:56:46: cvc-complex-type.2.4.a: Invalid content was found starting with element 'include'. One of '{key}' is expected.
[schemavalidate] hybris/bin/custom/sanecleanup/resources/sanecleanup-items.xml:67:46: cvc-complex-type.2.4.a: Invalid content was found starting with element 'include'. One of '{key}' is expected.
[schemavalidate] hybris/bin/custom/sanecleanup/resources/sanecleanup-items.xml:79:46: cvc-complex-type.2.4.a: Invalid content was found starting with element 'include'. One of '{key}' is expected.
[schemavalidate] hybris/bin/custom/sanecleanup/resources/sanecleanup-items.xml:89:46: cvc-complex-type.2.4.a: Invalid content was found starting with element 'include'. One of '{key}' is expected.
[schemavalidate] hybris/bin/custom/sanecleanup/resources/sanecleanup-items.xml:100:46: cvc-complex-type.2.4.a: Invalid content was found starting with element 'include'. One of '{key}' is expected.
[schemavalidate] hybris/bin/custom/sanecleanup/resources/sanecleanup-items.xml:110:46: cvc-complex-type.2.4.a: Invalid content was found starting with element 'include'. One of '{key}' is expected.
[schemavalidate] hybris/bin/custom/sanecleanup/resources/sanecleanup-items.xml:119:46: cvc-complex-type.2.4.a: Invalid content was found starting with element 'include'. One of '{key}' is expected.
[schemavalidate] hybris/bin/custom/sanecleanup/resources/sanecleanup-items.xml:130:46: cvc-complex-type.2.4.a: Invalid content was found starting with element 'include'. One of '{key}' is expected.
[schemavalidate] hybris/bin/custom/sanecleanup/resources/sanecleanup-items.xml:140:46: cvc-complex-type.2.4.a: Invalid content was found starting with element 'include'. One of '{key}' is expected.
[schemavalidate] hybris/bin/custom/sanecleanup/resources/sanecleanup-items.xml:150:46: cvc-complex-type.2.4.a: Invalid content was found starting with element 'include'. One of '{key}' is expected.
[schemavalidate] hybris/bin/custom/sanecleanup/resources/sanecleanup-items.xml:160:46: cvc-complex-type.2.4.a: Invalid content was found starting with element 'include'. One of '{key}' is expected.
[schemavalidate] hybris/bin/custom/sanecleanup/resources/sanecleanup-items.xml:170:46: cvc-complex-type.2.4.a: Invalid content was found starting with element 'include'. One of '{key}' is expected.
[schemavalidate] hybris/bin/custom/sanecleanup/resources/sanecleanup-items.xml:182:46: cvc-complex-type.2.4.a: Invalid content was found starting with element 'include'. One of '{key}' is expected.
[schemavalidate] hybris/bin/custom/sanecleanup/resources/sanecleanup-items.xml:193:46: cvc-complex-type.2.4.a: Invalid content was found starting with element 'include'. One of '{key}' is expected.
[schemavalidate] hybris/bin/custom/sanecleanup/resources/sanecleanup-items.xml:204:46: cvc-complex-type.2.4.a: Invalid content was found starting with element 'include'. One of '{key}' is expected.

BUILD FAILED

**Comment by mpern** [comment]
same as #5

Let me quote the [release notes](https://github.com/sap-commerce-tools/sanecleanup/releases/tag/v3.4.0):

> Experimental: Define DB indices to accelerate cleanup queries in CCv2
> **The minimum required versions for this feature are: [1905.33](https://help.sap.com/docs/SAP_COMMERCE_CLOUD_PUBLIC_CLOUD/75d4c3895cb346008545900bffe851ce/f18f6a711d07462b80137df6ed533eee.html?version=v1905#patch-1905.33), [2005.17](https://help.sap.com/docs/SAP_COMMERCE_CLOUD_PUBLIC_CLOUD/75d4c3895cb346008545900bffe851ce/f18f6a711d07462b80137df6ed533eee.html?version=v2005#patch-2005.17), [2011.12](https://help.sap.com/docs/SAP_COMMERCE_CLOUD_PUBLIC_CLOUD/75d4c3895cb346008545900bffe851ce/f18f6a711d07462b80137df6ed533eee.html?version=v2011#patch-2011.12), [2105.2](https://help.sap.com/docs/SAP_COMMERCE_CLOUD_PUBLIC_CLOUD/75d4c3895cb346008545900bffe851ce/f18f6a711d07462b80137df6ed533eee.html#patch-2105.2)**
> Please always make sure to stay on the latest patch release!
> In case of problems:
> 
> - Report an [issue](https://github.com/sap-commerce-tools/sanecleanup/issues) in this repository
> - Comment-out the offending type / index in `sanecleanup-items.xml`
