### ISSUE TITLE
Links to SAP Article are dead

### ISSUE THREAD

**Issue by lm-aols** [sap-commerce-tools/sanecleanup#7]
Hi Markus,

I would love to read your article that you reference multiple times, but the link no longer works.
Is the article available elsewhere, and can you update the links to point at the new url ?

Best regards
Anders Olsen

**Comment by mpern** [comment]
I'll update the links as soon as the new blog post gets published

**Comment by mpern** [comment]
https://blogs.sap.com/2023/09/20/data-maintenance-and-cleanup-of-a-sap-commerce-cloud-project/
